[package]
name = "mindless"
version = "0.1.0"
description = "A personal task management app"
authors = ["You"]
edition = "2021"

[lib]
name = "mindless_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-notification = "2"
tauri-plugin-dialog = "2"
tauri-plugin-positioner = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
uuid = { version = "1", features = ["v4", "v7", "serde"] }
rusqlite = { version = "0.31", features = ["bundled"] }
tauri-plugin-opener = "2"
window-shadows-v2 = "0.1.1"
keyring = "4"
sha2 = "0.10"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2.7"
